Changed `JacksonJSONSerializer` to catch `Throwable` to catch deserialization errors such as NoClassDefFoundError
(cherry picked from commit 432d3874fd09c1c41f996ea78220299f8f771d39)