Removed static fields in `StatefulAggregateInstanceFactory` to avoid `Objenesis` class dependencies if you're using the `reflectionBasedAggregateRootFactory()` Renamed `LocalDateColumnMapper` to `LocalDateTypeColumnMapper` Switched `DurableQueues` and `DefaultDurableQueueConsumer` to handle `Throwable` instead of Exception Introduced `EventProcessorDependencies` to simplify `EventProcessor` configuration and implementations Changed `JacksonJSONSerializer` to catch `Throwable` to catch deserialization errors such as NoClassDefFoundError Added versions section to root README.md Added a license section to the root README.md for clarity - Changed all classes to depend on either `JSONSerializer` or `JSONEventSerializer` instead of allow `ObjectMapper` as input parameter - Changed the default spring-boot-starters (Postgresql, EventStore and MongoDB) to encapsulate the `ObjectMapper` used by Essentials for `DurableQueues` message and `EventStore` `Event` JSON serialization.  - Instead the spring-boot-starter configures a `JacksonJSONSerializer` (Postgresql/MongoDB) or `JacksonJSONEventSerializer` (EventStore)  - The `EssentialTypesJacksonModule` is now defined as a `@Bean` such that it applies to the default `ObjectMapper` Added more clear warning that the types-jpa module is very experimental & unstable Refined the maven plugin configs Adjusted JPA tests - commented out `@ElementCollection` of `Order`'s `Map<ProductId, Quantity> orderLines` code as it doesn't work Added error logging to `EventProcessor` in case of JSON deserialization exception Added support for delayed message sending in `Inbox` and `Outbox`
Updated 3rd party dependencies
- testcontainers 1.19.4
- Junit 5.10.2
- jdbi 3.44.0
- Mockito 5.10.0
- micrometer 1.12.2
- micrometer-tracing 1.2.2
- netty 4.1.106.Final
- reactor 2020.0.40
- Updated to AssertJ 3.25.3